name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: sudo bash kubernetes.sh

      - name: Test override version
        run: sudo KUBECTL_VERSION=v1.25.4 bash kubernetes.sh
