name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  test-kubernetes:
    name: Test Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: sudo bash kubernetes.sh

      - name: Test override
        run: sudo KUBECTL_VERSION=v1.25.4 bash kubernetes.sh

  test-k9s:
    name: Test k9s
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: sudo bash k9s.sh -y

      - name: Test k9s override
        run: sudo K9S_VERSION=v0.32.4 bash k9s.sh -y